### ISSUE TITLE
SCD Subscription with no `time_start` crashes backend

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#360]
When a Subscription with no `time_start` is submitted, it crashes the gRPC backend:

```
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa79019] 
goroutine 613 [running]: 
github.com/interuss/dss/pkg/scd/models.(*Subscription).AdjustTimeRange(0xc0002a17c0, 0xbfbc97f482c5293d, 0x579a6f64475, 0x12cd920, 0xc0002a17c0, 0x0, 0x0) 
	/app/pkg/scd/models/subscriptions.go:113 +0x209 
github.com/interuss/dss/pkg/scd.(*Server).PutSubscription(0xc0000b4240, 0xd751e0, 0xc0002e2870, 0xc0005a4780, 0xc0000b4240, 0x0, 0xc00094c9a0) 
	/app/pkg/scd/subscriptions_handler.go:77 +0x3f3 
github.com/interuss/dss/pkg/api/v1/scdpb._UTMAPIUSSDSSAndUSSUSSService_PutSubscription_Handler.func1(0xd751e0, 0xc0002e2870, 0xbc8640, 0xc0005a4780, 0xc00045cbf0, 0x2, 0x2, 0x0) 
	/app/pkg/api/v1/scdpb/scd.pb.go:5681 +0x86 
```

**Comment by pratibhagupta2109** [comment]
Issue is already fixed. Test cases are updated in #558
